#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-pkgbuild
Version  : 1.0.2
Release  : 6
URL      : https://cran.r-project.org/src/contrib/pkgbuild_1.0.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pkgbuild_1.0.2.tar.gz
Summary  : Find Tools Needed to Build R Packages
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
BuildRequires : R-Rcpp
BuildRequires : R-assertthat
BuildRequires : R-callr
BuildRequires : R-cli
BuildRequires : R-desc
BuildRequires : R-prettyunits
BuildRequires : R-ps
BuildRequires : R-rlang
BuildRequires : R-rprojroot
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
needed to build R packages on various platforms and ensures the PATH is
  configured appropriately so R can use them.

%prep
%setup -q -c -n pkgbuild

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539747238

%install
export SOURCE_DATE_EPOCH=1539747238
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgbuild
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgbuild
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgbuild
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library pkgbuild|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pkgbuild/DESCRIPTION
/usr/lib64/R/library/pkgbuild/INDEX
/usr/lib64/R/library/pkgbuild/Meta/Rd.rds
/usr/lib64/R/library/pkgbuild/Meta/features.rds
/usr/lib64/R/library/pkgbuild/Meta/hsearch.rds
/usr/lib64/R/library/pkgbuild/Meta/links.rds
/usr/lib64/R/library/pkgbuild/Meta/nsInfo.rds
/usr/lib64/R/library/pkgbuild/Meta/package.rds
/usr/lib64/R/library/pkgbuild/NAMESPACE
/usr/lib64/R/library/pkgbuild/NEWS.md
/usr/lib64/R/library/pkgbuild/R/pkgbuild
/usr/lib64/R/library/pkgbuild/R/pkgbuild.rdb
/usr/lib64/R/library/pkgbuild/R/pkgbuild.rdx
/usr/lib64/R/library/pkgbuild/help/AnIndex
/usr/lib64/R/library/pkgbuild/help/aliases.rds
/usr/lib64/R/library/pkgbuild/help/paths.rds
/usr/lib64/R/library/pkgbuild/help/pkgbuild.rdb
/usr/lib64/R/library/pkgbuild/help/pkgbuild.rdx
/usr/lib64/R/library/pkgbuild/html/00Index.html
/usr/lib64/R/library/pkgbuild/html/R.css
/usr/lib64/R/library/testDummy/DESCRIPTION
/usr/lib64/R/library/testDummy/Meta/Rd.rds
/usr/lib64/R/library/testDummy/Meta/features.rds
/usr/lib64/R/library/testDummy/Meta/hsearch.rds
/usr/lib64/R/library/testDummy/Meta/links.rds
/usr/lib64/R/library/testDummy/Meta/nsInfo.rds
/usr/lib64/R/library/testDummy/Meta/package.rds
/usr/lib64/R/library/testDummy/NAMESPACE
/usr/lib64/R/library/testDummy/R/testDummy
/usr/lib64/R/library/testDummy/R/testDummy.rdb
/usr/lib64/R/library/testDummy/R/testDummy.rdx
/usr/lib64/R/library/testDummy/help/AnIndex
/usr/lib64/R/library/testDummy/help/aliases.rds
/usr/lib64/R/library/testDummy/help/paths.rds
/usr/lib64/R/library/testDummy/help/testDummy.rdb
/usr/lib64/R/library/testDummy/help/testDummy.rdx
/usr/lib64/R/library/testDummy/html/00Index.html
/usr/lib64/R/library/testDummy/html/R.css
